FROM python:3.9
 
WORKDIR /app

COPY requirements.txt /app
 
RUN pip install -r /app/requirements.txt
COPY . /app

# RUN alembic upgrade head

# CMD ["uvicorn", "src.main.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]