version: '3'

services:
  backend:
    container_name: backend
    restart: on-failure
    build: 
      context: .
    ports:
      - 8000:8000
    depends_on:
      - db
    command: ["uvicorn", "src.main.main:app", "--reload"]
    env_file:
      - .env
  db:
    image: postgres:16
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=RainBow6"
      - "DB_HOST=localhost"
      - "DB_PORT=5432"
      - "DB_NAME=paradox"
    container_name: db_app
