"""create index

Revision ID: 2d1f5115ffb2
Revises: 1b2cef1fcea7
Create Date: 2024-08-23 18:01:08.135291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import func

from src.data.models.product import ProductModel


# revision identifiers, used by Alembic.
revision: str = '2d1f5115ffb2'
down_revision: Union[str, None] = '1b2cef1fcea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

index = sa.Index(
        'product_name_game_category_index',
        (
            func.coalesce(ProductModel.name, '')
            .concat(func.coalesce(ProductModel.game, '')
            .concat(func.coalesce(ProductModel.category, ''))).label('columns')
        ),
        postgresql_using='gin',
        postgresql_ops={
            'columns': 'gin_trgm_ops',
        },
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    op.drop_index('article_title_body_trgm_idx', table_name='product', postgresql_using='gin')
    # op.create_index('article_title_body_trgm_idx', 'product', [sa.text("(coalesce(name, '') || coalesce(description, '') || coalesce(game, '') || coalesce(category, ''))")], unique=False, postgresql_using='gin', postgresql_ops={'columns': 'gin_trgm_ops'})
    # op.create_index('product_name_game_category_index', 'product', [sa.text("(coalesce(name, '') || coalesce(game, '') || coalesce(category, ''))")], unique=False, postgresql_using='gin', postgresql_ops={'columns': 'gin_trgm_ops'})
    op.create_index(
        index.name,
        index.table.name,
        index.expressions,
        postgresql_using='gin',
        postgresql_ops={'columns': 'gin_trgm_ops'},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('product_name_game_category_index', table_name='product', postgresql_using='gin', postgresql_ops={'columns': 'gin_trgm_ops'})
    op.drop_index('article_title_body_trgm_idx', table_name='product', postgresql_using='gin', postgresql_ops={'columns': 'gin_trgm_ops'})
    op.create_index('article_title_body_trgm_idx', 'product', [sa.text("(((COALESCE(name, ''::character varying)::text || COALESCE(description, ''::character varying)::text) || COALESCE(game, ''::character varying)::text) || COALESCE(category, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    op.create_table('article',

    )
    # ### end Alembic commands ###
