"""rename 'coupon' to 'promo'

Revision ID: 517649234672
Revises: 297244ea703e
Create Date: 2024-08-03 16:19:30.610619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '517649234672'
down_revision: Union[str, None] = '297244ea703e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bonus_amount', sa.DECIMAL(), nullable=False),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='promostatus'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('coupon')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupon',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bonus_amount', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('uses', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', name='couponstatus'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='coupon_pkey'),
    sa.UniqueConstraint('name', name='coupon_name_key')
    )
    op.drop_table('promo')
    # ### end Alembic commands ###
