"""add purchase count

Revision ID: c0abe4933eb2
Revises: 169643ef1165
Create Date: 2024-07-30 15:20:29.583306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0abe4933eb2'
down_revision: Union[str, None] = '169643ef1165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('purchase_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'purchase_count')
    # ### end Alembic commands ###
