"""add inde

Revision ID: 1b2cef1fcea7
Revises: 8d19fbe961f6
Create Date: 2024-08-22 18:51:35.279774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Index, func

from src.data.models import ProductModel


# revision identifiers, used by Alembic.
revision: str = '1b2cef1fcea7'
down_revision: Union[str, None] = '8d19fbe961f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

index = Index(
	'article_title_body_trgm_idx',

	# индекс необходимо строить по вызову точно такой же функции,
	# что будет использована при поисковом запросе
(
        func.coalesce(ProductModel.name, '')
                    .concat(
                        func.coalesce(ProductModel.description, '')
                        .concat(
                            func.coalesce(ProductModel.game, '')
                            .concat(
                                func.coalesce(ProductModel.category, '')
                            )
                        )
                    ).label('columns')
    ),

	# так же для индекса GIN нужно указать параметр gin_trgm_ops,
	# так Postgres поймет,что индекс нужно строить по Триграммам
	postgresql_using='gin',
	postgresql_ops={
		'columns': 'gin_trgm_ops',
	},
)

def upgrade() -> None:
    op.create_table('article', ...)
    op.create_index(
        index.name,
        index.table.name,
        index.expressions,
        postgresql_using='gin',
        postgresql_ops={'columns': 'gin_trgm_ops'},
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
