"""empty message

Revision ID: 8d69eb372069
Revises: 82a70d049130
Create Date: 2024-08-06 13:22:43.542072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d69eb372069'
down_revision: Union[str, None] = '82a70d049130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('product_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'feedback', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_column('feedback', 'product_id')
    # ### end Alembic commands ###
