"""add additional_data column

Revision ID: 297244ea703e
Revises: c0abe4933eb2
Create Date: 2024-08-03 14:56:21.771548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '297244ea703e'
down_revision: Union[str, None] = 'c0abe4933eb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('product_id', sa.UUID(), nullable=False))
    op.add_column('order', sa.Column('additional_data', sa.JSON(), nullable=True))
    op.alter_column('order', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'order', 'product', ['product_id'], ['id'])
    op.drop_column('order', 'email')
    op.drop_column('order', 'supercell_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('supercell_code', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.alter_column('order', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('order', 'additional_data')
    op.drop_column('order', 'product_id')
    # ### end Alembic commands ###
