"""empty message

Revision ID: cee6fc9251f1
Revises: b0c28836f3ef
Create Date: 2024-08-13 14:44:54.062473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cee6fc9251f1'
down_revision: Union[str, None] = 'b0c28836f3ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'status',
               existing_type=postgresql.ENUM('PAID', 'CLOSED', 'COMPLETED', name='orderstatus'),
               type_=sa.Enum('paid', 'closed', 'completed', 'progress', name='orderstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'status',
               existing_type=sa.Enum('paid', 'closed', 'completed', 'progress', name='order_status_enum'),
               type_=postgresql.ENUM('PAID', 'CLOSED', 'COMPLETED', name='orderstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
