"""default param for balance - 0

Revision ID: 3d6178a726d8
Revises: 310364b28808
Create Date: 2024-08-13 11:50:53.207859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d6178a726d8'
down_revision: Union[str, None] = '310364b28808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'balance',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'balance',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###
