"""empty message

Revision ID: 310364b28808
Revises: e466e566b1c3
Create Date: 2024-08-13 11:45:33.255584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '310364b28808'
down_revision: Union[str, None] = 'e466e566b1c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False,
            #    autoincrement=True,
               existing_server_default=sa.text("nextval('user_user_id_seq'::regclass)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_id',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False,
            #    autoincrement=True,
               existing_server_default=sa.text("nextval('user_user_id_seq'::regclass)"))
    # ### end Alembic commands ###
