"""empty message

Revision ID: 8d19fbe961f6
Revises: 63395c455a5a
Create Date: 2024-08-16 13:39:25.620427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d19fbe961f6'
down_revision: Union[str, None] = '63395c455a5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('payment_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'payment_data')
    # ### end Alembic commands ###
