"""empty message

Revision ID: 63395c455a5a
Revises: cee6fc9251f1
Create Date: 2024-08-14 13:09:24.469009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63395c455a5a'
down_revision: Union[str, None] = 'cee6fc9251f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('game', sa.String(), nullable=True))
    op.add_column('product', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'category')
    op.drop_column('product', 'game')
    # ### end Alembic commands ###
