"""empty message

Revision ID: 7d299bc5609b
Revises: 3d6178a726d8
Create Date: 2024-08-13 11:58:00.458326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d299bc5609b'
down_revision: Union[str, None] = '3d6178a726d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.BigInteger(),
               existing_nullable=False,
            #    autoincrement=False,
               existing_server_default=sa.text("nextval('user_user_id_seq'::regclass)"))
    op.alter_column('user', 'balance',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'balance',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('user', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(),
               existing_nullable=False,
               autoincrement=False,
               existing_server_default=sa.text("nextval('user_user_id_seq'::regclass)"))
    # ### end Alembic commands ###
